name: Release Gem

on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/ruby_test.yml
    with:
      ruby-version: '3.4.2'

  release:
    name: Release to RubyGems
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Publish the gem to RubyGems
      # Reference: https://docs.github.com/ja/actions/use-cases-and-examples/building-and-testing/building-and-testing-ruby#publishing-gems
      - name: Publish to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          cd ruby
          mkdir -p .gem
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > .gem/credentials
          chmod 0600 .gem/credentials
          gem build simple_inline_text_annotation.gemspec
          gem push simple_inline_text_annotation-*.gem --config-file .gem/credentials
