name: Ruby

on:
  push:
    branches:
      - main
    paths:
      - 'ruby/**'

  pull_request:
    paths:
      - 'ruby/**'

jobs:
  test:
    uses: ./.github/workflows/ruby_test.yml
    with:
      ruby-version: '3.4.4'
